# Generated by Django 2.2 on 2024-08-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complant_id', models.CharField(max_length=200)),
                ('give_by', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='employee_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('aadhar_no', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('date_join', models.CharField(max_length=200)),
                ('work_type', models.CharField(max_length=200)),
                ('mobile_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Food_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200)),
                ('food_type', models.CharField(max_length=200)),
                ('timing', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='incharge_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(max_length=200)),
                ('incharge_name', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('form_date', models.CharField(max_length=200)),
                ('till_date', models.CharField(max_length=200)),
                ('timing', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('city_type', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('moblie_no', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='servicedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('cost', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='shop_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=200)),
                ('shop_type', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('utype', models.CharField(max_length=50)),
            ],
        ),
    ]
